export const keywordDatabase: Record<
  string,
  {
    synonyms: string[];
    related: string[];
    searchTerms: string[];
    trending: string[];
    popularity: number;
    engagement: number;
  }
> = {
  ai: {
    synonyms: [
      'artificial intelligence',
      'machine learning',
      'automation',
      'robot',
      'smart',
      'intelligent',
    ],
    related: [
      'tech',
      'future',
      'innovation',
      'digital',
      'algorithm',
      'data',
      'coding',
      'programming',
    ],
    searchTerms: [
      'ai tutorial',
      'artificial intelligence explained',
      'machine learning basics',
      'ai tools',
    ],
    trending: [
      'chatgpt',
      'openai',
      'aitools',
      'machinelearning',
      'artificialintelligence',
      'automation',
    ],
    popularity: 95,
    engagement: 8.5,
  },
  technology: {
    synonyms: [
      'tech',
      'digital',
      'innovation',
      'software',
      'hardware',
      'gadget',
    ],
    related: [
      'ai',
      'coding',
      'programming',
      'app',
      'website',
      'computer',
      'mobile',
      'internet',
    ],
    searchTerms: [
      'tech review',
      'latest technology',
      'tech news',
      'gadget unboxing',
    ],
    trending: [
      'tech2024',
      'innovation',
      'digitaltransformation',
      'techreview',
      'gadgets',
      'software',
    ],
    popularity: 88,
    engagement: 7.2,
  },
  business: {
    synonyms: [
      'entrepreneur',
      'startup',
      'company',
      'corporate',
      'enterprise',
      'commerce',
    ],
    related: [
      'marketing',
      'sales',
      'money',
      'finance',
      'leadership',
      'strategy',
      'growth',
      'success',
    ],
    searchTerms: [
      'business tips',
      'startup advice',
      'entrepreneurship',
      'business growth',
    ],
    trending: [
      'entrepreneur',
      'startup',
      'businesstips',
      'success',
      'leadership',
      'marketing',
    ],
    popularity: 82,
    engagement: 6.8,
  },
  fitness: {
    synonyms: ['workout', 'exercise', 'training', 'gym', 'health', 'wellness'],
    related: [
      'nutrition',
      'diet',
      'strength',
      'cardio',
      'yoga',
      'running',
      'muscle',
      'weight',
    ],
    searchTerms: [
      'workout routine',
      'fitness tips',
      'exercise tutorial',
      'gym workout',
    ],
    trending: [
      'fitness',
      'workout',
      'gym',
      'health',
      'wellness',
      'fitnessmotivation',
      'exercise',
    ],
    popularity: 90,
    engagement: 8.1,
  },
  food: {
    synonyms: ['cooking', 'recipe', 'cuisine', 'meal', 'dish', 'kitchen'],
    related: [
      'chef',
      'ingredients',
      'healthy',
      'delicious',
      'restaurant',
      'baking',
      'nutrition',
    ],
    searchTerms: [
      'easy recipes',
      'cooking tutorial',
      'food review',
      'healthy meals',
    ],
    trending: [
      'foodie',
      'recipe',
      'cooking',
      'healthyfood',
      'delicious',
      'homecooking',
      'chef',
    ],
    popularity: 85,
    engagement: 7.9,
  },
  travel: {
    synonyms: [
      'adventure',
      'journey',
      'trip',
      'vacation',
      'explore',
      'wanderlust',
    ],
    related: [
      'destination',
      'culture',
      'photography',
      'nature',
      'city',
      'country',
      'experience',
    ],
    searchTerms: [
      'travel guide',
      'travel tips',
      'travel vlog',
      'destination guide',
    ],
    trending: [
      'travel',
      'adventure',
      'explore',
      'wanderlust',
      'vacation',
      'travelgram',
      'destination',
    ],
    popularity: 87,
    engagement: 8.3,
  },
  gaming: {
    synonyms: ['game', 'gamer', 'play', 'video game', 'esports'],
    related: [
      'streaming',
      'twitch',
      'youtube',
      'console',
      'pc',
      'mobile',
      'tournament',
    ],
    searchTerms: ['gaming tutorial', 'game review', 'gaming tips', 'gameplay'],
    trending: [
      'gaming',
      'gamer',
      'gameplay',
      'gamereview',
      'esports',
      'streaming',
      'videogames',
    ],
    popularity: 92,
    engagement: 8.7,
  },
  tutorial: {
    synonyms: ['guide', 'howto', 'lesson', 'course', 'training', 'education'],
    related: ['learning', 'tips', 'beginner', 'step by step', 'easy', 'quick'],
    searchTerms: ['tutorial', 'how to', 'beginner guide', 'step by step'],
    trending: [
      'tutorial',
      'howto',
      'guide',
      'tips',
      'learn',
      'education',
      'beginner',
    ],
    popularity: 78,
    engagement: 6.5,
  },
  lifestyle: {
    synonyms: ['life', 'daily', 'routine', 'personal', 'living'],
    related: [
      'home',
      'family',
      'wellness',
      'productivity',
      'habits',
      'mindset',
    ],
    searchTerms: [
      'lifestyle tips',
      'daily routine',
      'life advice',
      'personal development',
    ],
    trending: [
      'lifestyle',
      'dailyroutine',
      'selfcare',
      'productivity',
      'mindset',
      'wellness',
    ],
    popularity: 75,
    engagement: 6.2,
  },
  art: {
    synonyms: ['creative', 'design', 'artistic', 'drawing', 'painting'],
    related: [
      'creativity',
      'inspiration',
      'visual',
      'color',
      'sketch',
      'digital art',
    ],
    searchTerms: [
      'art tutorial',
      'drawing tips',
      'creative process',
      'art techniques',
    ],
    trending: [
      'art',
      'artist',
      'creative',
      'drawing',
      'painting',
      'digitalart',
      'artwork',
    ],
    popularity: 73,
    engagement: 7.1,
  },
  fashion: {
    synonyms: ['style', 'outfit', 'clothing', 'trendy', 'chic'],
    related: ['beauty', 'makeup', 'accessories', 'designer', 'trend', 'look'],
    searchTerms: [
      'fashion tips',
      'style guide',
      'outfit ideas',
      'fashion trends',
    ],
    trending: [
      'fashion',
      'style',
      'outfit',
      'ootd',
      'fashionista',
      'trendy',
      'stylish',
    ],
    popularity: 80,
    engagement: 7.6,
  },
  music: {
    synonyms: ['song', 'audio', 'sound', 'melody', 'rhythm'],
    related: [
      'artist',
      'musician',
      'instrument',
      'concert',
      'album',
      'playlist',
    ],
    searchTerms: [
      'music tutorial',
      'song cover',
      'music review',
      'how to play',
    ],
    trending: [
      'music',
      'song',
      'musician',
      'cover',
      'playlist',
      'newmusic',
      'artist',
    ],
    popularity: 84,
    engagement: 7.8,
  },
  // NEW CATEGORIES BELOW
  cryptocurrency: {
    synonyms: [
      'crypto',
      'bitcoin',
      'blockchain',
      'digital currency',
      'altcoin',
      'defi',
    ],
    related: [
      'investment',
      'trading',
      'finance',
      'technology',
      'money',
      'wallet',
      'mining',
    ],
    searchTerms: [
      'crypto news',
      'bitcoin price',
      'blockchain explained',
      'crypto trading',
    ],
    trending: [
      'bitcoin',
      'ethereum',
      'crypto',
      'blockchain',
      'defi',
      'nft',
      'web3',
    ],
    popularity: 89,
    engagement: 8.4,
  },
  photography: {
    synonyms: ['photo', 'camera', 'shot', 'picture', 'image', 'visual'],
    related: [
      'editing',
      'lightroom',
      'photoshop',
      'portrait',
      'landscape',
      'studio',
      'lens',
    ],
    searchTerms: [
      'photography tips',
      'camera tutorial',
      'photo editing',
      'photography basics',
    ],
    trending: [
      'photography',
      'photooftheday',
      'photographer',
      'photoshoot',
      'camera',
      'portrait',
    ],
    popularity: 81,
    engagement: 7.4,
  },
  health: {
    synonyms: [
      'wellness',
      'medical',
      'healthcare',
      'medicine',
      'wellbeing',
      'healing',
    ],
    related: [
      'fitness',
      'nutrition',
      'mental health',
      'doctor',
      'treatment',
      'prevention',
    ],
    searchTerms: [
      'health tips',
      'medical advice',
      'wellness guide',
      'health information',
    ],
    trending: [
      'health',
      'wellness',
      'mentalhealth',
      'healthcare',
      'nutrition',
      'selfcare',
    ],
    popularity: 86,
    engagement: 7.7,
  },
  mentalhealth: {
    synonyms: [
      'psychology',
      'therapy',
      'mindfulness',
      'stress',
      'anxiety',
      'depression',
    ],
    related: [
      'wellness',
      'meditation',
      'counseling',
      'support',
      'healing',
      'mindset',
    ],
    searchTerms: [
      'mental health tips',
      'anxiety help',
      'stress management',
      'therapy advice',
    ],
    trending: [
      'mentalhealth',
      'selfcare',
      'therapy',
      'mindfulness',
      'wellness',
      'meditation',
    ],
    popularity: 83,
    engagement: 8.2,
  },
  finance: {
    synonyms: [
      'money',
      'investment',
      'financial',
      'budget',
      'savings',
      'economy',
    ],
    related: [
      'business',
      'trading',
      'banking',
      'retirement',
      'wealth',
      'debt',
      'income',
    ],
    searchTerms: [
      'financial advice',
      'investment tips',
      'budgeting guide',
      'money management',
    ],
    trending: [
      'finance',
      'investing',
      'money',
      'budget',
      'savings',
      'financialfreedom',
    ],
    popularity: 79,
    engagement: 6.9,
  },
  education: {
    synonyms: [
      'learning',
      'school',
      'study',
      'academic',
      'knowledge',
      'teaching',
    ],
    related: [
      'tutorial',
      'course',
      'university',
      'student',
      'teacher',
      'research',
      'exam',
    ],
    searchTerms: [
      'study tips',
      'educational content',
      'learning methods',
      'academic help',
    ],
    trending: [
      'education',
      'learning',
      'study',
      'students',
      'teacher',
      'school',
      'knowledge',
    ],
    popularity: 74,
    engagement: 6.6,
  },
  parenting: {
    synonyms: [
      'family',
      'kids',
      'children',
      'mom',
      'dad',
      'parent',
      'childcare',
    ],
    related: [
      'baby',
      'toddler',
      'teenager',
      'education',
      'development',
      'activities',
    ],
    searchTerms: [
      'parenting tips',
      'child development',
      'family activities',
      'parenting advice',
    ],
    trending: [
      'parenting',
      'kids',
      'family',
      'mom',
      'dad',
      'children',
      'parenthood',
    ],
    popularity: 77,
    engagement: 7.3,
  },
  relationships: {
    synonyms: [
      'love',
      'dating',
      'marriage',
      'friendship',
      'romance',
      'partnership',
    ],
    related: [
      'communication',
      'trust',
      'intimacy',
      'conflict',
      'support',
      'connection',
    ],
    searchTerms: [
      'relationship advice',
      'dating tips',
      'marriage counseling',
      'love advice',
    ],
    trending: [
      'relationships',
      'love',
      'dating',
      'marriage',
      'friendship',
      'couples',
    ],
    popularity: 76,
    engagement: 7.5,
  },
  science: {
    synonyms: [
      'research',
      'study',
      'experiment',
      'discovery',
      'theory',
      'analysis',
    ],
    related: [
      'technology',
      'innovation',
      'facts',
      'data',
      'knowledge',
      'physics',
      'biology',
    ],
    searchTerms: [
      'science news',
      'scientific research',
      'science explained',
      'discoveries',
    ],
    trending: [
      'science',
      'research',
      'discovery',
      'experiment',
      'scientific',
      'innovation',
    ],
    popularity: 72,
    engagement: 6.8,
  },
  environment: {
    synonyms: [
      'nature',
      'climate',
      'sustainability',
      'green',
      'eco',
      'conservation',
    ],
    related: [
      'earth',
      'pollution',
      'renewable',
      'recycling',
      'wildlife',
      'planet',
    ],
    searchTerms: [
      'environmental news',
      'climate change',
      'sustainability tips',
      'eco friendly',
    ],
    trending: [
      'environment',
      'climatechange',
      'sustainability',
      'green',
      'nature',
      'eco',
    ],
    popularity: 71,
    engagement: 6.7,
  },
  psychology: {
    synonyms: [
      'mind',
      'behavior',
      'mental',
      'cognitive',
      'emotion',
      'psychological',
    ],
    related: [
      'therapy',
      'consciousness',
      'personality',
      'development',
      'learning',
      'brain',
    ],
    searchTerms: [
      'psychology facts',
      'human behavior',
      'mental health',
      'psychology tips',
    ],
    trending: [
      'psychology',
      'mentalhealth',
      'mindset',
      'behavior',
      'therapy',
      'consciousness',
    ],
    popularity: 78,
    engagement: 7.2,
  },
  productivity: {
    synonyms: [
      'efficiency',
      'organization',
      'workflow',
      'time management',
      'focus',
    ],
    related: [
      'habits',
      'goals',
      'planning',
      'success',
      'motivation',
      'tools',
      'systems',
    ],
    searchTerms: [
      'productivity tips',
      'time management',
      'organization hacks',
      'productivity tools',
    ],
    trending: [
      'productivity',
      'timemanagement',
      'organization',
      'efficiency',
      'goals',
      'habits',
    ],
    popularity: 82,
    engagement: 7.1,
  },
  motivation: {
    synonyms: [
      'inspiration',
      'success',
      'goals',
      'achievement',
      'drive',
      'ambition',
    ],
    related: [
      'mindset',
      'habits',
      'personal development',
      'leadership',
      'growth',
    ],
    searchTerms: [
      'motivational quotes',
      'success tips',
      'goal setting',
      'inspiration',
    ],
    trending: [
      'motivation',
      'success',
      'goals',
      'inspiration',
      'mindset',
      'achievement',
    ],
    popularity: 85,
    engagement: 8.0,
  },
  sports: {
    synonyms: ['athletics', 'competition', 'team', 'player', 'match', 'game'],
    related: [
      'fitness',
      'training',
      'athlete',
      'championship',
      'tournament',
      'exercise',
    ],
    searchTerms: [
      'sports news',
      'game highlights',
      'athlete training',
      'sports analysis',
    ],
    trending: [
      'sports',
      'football',
      'basketball',
      'soccer',
      'athletics',
      'championship',
    ],
    popularity: 88,
    engagement: 8.3,
  },
  movies: {
    synonyms: [
      'film',
      'cinema',
      'movie',
      'entertainment',
      'Hollywood',
      'actor',
    ],
    related: ['review', 'trailer', 'director', 'genre', 'streaming', 'theater'],
    searchTerms: [
      'movie review',
      'film analysis',
      'movie trailer',
      'cinema news',
    ],
    trending: [
      'movies',
      'film',
      'cinema',
      'moviereview',
      'hollywood',
      'streaming',
    ],
    popularity: 84,
    engagement: 7.9,
  },
  books: {
    synonyms: ['reading', 'literature', 'novel', 'author', 'story', 'writing'],
    related: [
      'education',
      'knowledge',
      'review',
      'fiction',
      'non-fiction',
      'library',
    ],
    searchTerms: [
      'book review',
      'reading list',
      'book recommendations',
      'author interview',
    ],
    trending: [
      'books',
      'reading',
      'bookreview',
      'author',
      'literature',
      'bookclub',
    ],
    popularity: 69,
    engagement: 6.4,
  },
  diy: {
    synonyms: [
      'do it yourself',
      'craft',
      'handmade',
      'project',
      'creative',
      'build',
    ],
    related: [
      'tutorial',
      'tools',
      'materials',
      'home improvement',
      'repair',
      'making',
    ],
    searchTerms: [
      'diy projects',
      'craft tutorial',
      'diy ideas',
      'handmade crafts',
    ],
    trending: [
      'diy',
      'crafts',
      'handmade',
      'diyproject',
      'creative',
      'crafting',
    ],
    popularity: 76,
    engagement: 7.6,
  },
  home: {
    synonyms: ['house', 'interior', 'decoration', 'design', 'living', 'space'],
    related: [
      'furniture',
      'decor',
      'organization',
      'cleaning',
      'renovation',
      'garden',
    ],
    searchTerms: [
      'home decor',
      'interior design',
      'home improvement',
      'house tour',
    ],
    trending: [
      'homedecor',
      'interiordesign',
      'home',
      'decoration',
      'homeimprovement',
    ],
    popularity: 78,
    engagement: 7.3,
  },
  // beauty: {
  //   synonyms: ["makeup", "skincare", "cosmetics", "beauty", "glamour", "style"],
  //   related: ["fashion", "hair", "nails", "products", "routine", "tips"],
  //   searchTerms: ["beauty tips", "makeup tutorial", "skincare routine", "beauty products"],
  //   // traveling: ["beauty", "makeup", "skincare", "beautytips", "cosmetics", "makeuptutorial"],
  //   popularity: 83,
  //   engagement: 8.1,
  // },
  pets: {
    synonyms: ['animals', 'dog', 'cat', 'pet care', 'companion', 'furry'],
    related: ['training', 'health', 'food', 'toys', 'veterinary', 'behavior'],
    searchTerms: ['pet care', 'dog training', 'cat behavior', 'pet health'],
    trending: ['pets', 'dogs', 'cats', 'petcare', 'animals', 'dogtraining'],
    popularity: 81,
    engagement: 8.0,
  },
  cars: {
    synonyms: [
      'automobile',
      'vehicle',
      'automotive',
      'driving',
      'motor',
      'transportation',
    ],
    related: [
      'maintenance',
      'repair',
      'racing',
      'electric',
      'luxury',
      'review',
    ],
    searchTerms: [
      'car review',
      'automotive news',
      'car maintenance',
      'driving tips',
    ],
    trending: [
      'cars',
      'automotive',
      'electriccars',
      'carreview',
      'driving',
      'vehicles',
    ],
    popularity: 79,
    engagement: 7.2,
  },
  news: {
    synonyms: [
      'current events',
      'breaking',
      'headlines',
      'journalism',
      'media',
      'updates',
    ],
    related: [
      'politics',
      'world',
      'local',
      'international',
      'analysis',
      'reporting',
    ],
    searchTerms: ['breaking news', 'current events', 'news today', 'headlines'],
    trending: [
      'news',
      'breakingnews',
      'headlines',
      'currentevents',
      'updates',
      'media',
    ],
    popularity: 87,
    engagement: 7.8,
  },
  comedy: {
    synonyms: [
      'humor',
      'funny',
      'jokes',
      'entertainment',
      'laughter',
      'satire',
    ],
    related: [
      'memes',
      'standup',
      'comedy',
      'entertaining',
      'hilarious',
      'amusing',
    ],
    searchTerms: ['funny videos', 'comedy shows', 'jokes', 'humor'],
    trending: ['comedy', 'funny', 'humor', 'memes', 'jokes', 'entertainment'],
    popularity: 86,
    engagement: 8.6,
  },
  mindfulness: {
    synonyms: [
      'meditation',
      'awareness',
      'present',
      'zen',
      'consciousness',
      'peace',
    ],
    related: [
      'mental health',
      'wellness',
      'spirituality',
      'calm',
      'relaxation',
      'focus',
    ],
    searchTerms: [
      'mindfulness meditation',
      'mindful living',
      'meditation guide',
      'mindfulness tips',
    ],
    trending: [
      'mindfulness',
      'meditation',
      'wellness',
      'mentalhealth',
      'selfcare',
      'peace',
    ],
    popularity: 74,
    engagement: 7.4,
  },
  investing: {
    synonyms: [
      'investment',
      'stocks',
      'portfolio',
      'trading',
      'wealth',
      'financial',
    ],
    related: ['finance', 'money', 'market', 'retirement', 'savings', 'economy'],
    searchTerms: [
      'investment tips',
      'stock market',
      'investing guide',
      'portfolio management',
    ],
    trending: [
      'investing',
      'stocks',
      'investment',
      'trading',
      'finance',
      'wealth',
    ],
    popularity: 80,
    engagement: 7.1,
  },
  real_estate: {
    synonyms: [
      'property',
      'housing',
      'real estate',
      'mortgage',
      'buying',
      'selling',
    ],
    related: [
      'investment',
      'market',
      'home',
      'rental',
      'commercial',
      'development',
    ],
    searchTerms: [
      'real estate tips',
      'property investment',
      'home buying',
      'real estate market',
    ],
    trending: [
      'realestate',
      'property',
      'housing',
      'homebuying',
      'investment',
      'mortgage',
    ],
    popularity: 73,
    engagement: 6.5,
  },
  networking: {
    synonyms: [
      'connections',
      'professional',
      'career',
      'business relationships',
      'contacts',
    ],
    related: [
      'career',
      'business',
      'professional development',
      'social',
      'communication',
    ],
    searchTerms: [
      'networking tips',
      'professional networking',
      'career networking',
      'business connections',
    ],
    trending: [
      'networking',
      'professional',
      'career',
      'business',
      'connections',
      'linkedin',
    ],
    popularity: 67,
    engagement: 6.3,
  },
  career: {
    synonyms: [
      'job',
      'profession',
      'work',
      'employment',
      'professional',
      'occupation',
    ],
    related: [
      'resume',
      'interview',
      'salary',
      'promotion',
      'skills',
      'development',
    ],
    searchTerms: [
      'career advice',
      'job search',
      'career development',
      'professional growth',
    ],
    trending: [
      'career',
      'job',
      'professional',
      'work',
      'careeradvice',
      'employment',
    ],
    popularity: 76,
    engagement: 6.8,
  },
  weather: {
    synonyms: ['climate', 'forecast', 'temperature', 'rain', 'sunny', 'storm'],
    related: [
      'environment',
      'seasons',
      'nature',
      'outdoor',
      'travel',
      'planning',
    ],
    searchTerms: [
      'weather forecast',
      'weather update',
      'climate news',
      'weather report',
    ],
    trending: [
      'weather',
      'forecast',
      'climate',
      'storm',
      'temperature',
      'rain',
    ],
    popularity: 65,
    engagement: 5.8,
  },
};
