export const platformStrategies = {
  youtube: {
    maxHashtags: 15,
    trending: [
      '#shorts',
      '#viral',
      '#trending',
      '#youtube',
      '#subscribe',
      '#2024',
      '#new',
    ],
    contentTypes: [
      '#tutorial',
      '#howto',
      '#review',
      '#unboxing',
      '#tips',
      '#guide',
      '#vlog',
    ],
    characterLimit: 500,
  },
  facebook: {
    maxHashtags: 8,
    trending: [
      '#facebook',
      '#social',
      '#community',
      '#share',
      '#connect',
      '#local',
    ],
    contentTypes: [
      '#news',
      '#update',
      '#community',
      '#family',
      '#friends',
      '#local',
    ],
    characterLimit: 63206,
  },
  instagram: {
    maxHashtags: 30,
    trending: [
      '#instagram',
      '#insta',
      '#instagood',
      '#photooftheday',
      '#love',
      '#beautiful',
      '#happy',
      '#follow',
      '#like4like',
      '#instadaily',
    ],
    contentTypes: [
      '#photo',
      '#pic',
      '#selfie',
      '#ootd',
      '#mood',
      '#vibes',
      '#aesthetic',
      '#art',
    ],
    characterLimit: 2200,
  },
};
